### PR TITLE
Generate random RGB/Gray arrays

### PR DESCRIPTION
**Pull request by timholy**
This seems like long-overdue functionality. My only real question is whether this belongs here, Colors, or ColorTypes.

### CODE REVIEW

**Comment by mronian** [comment]
Thanks a lot for this!

**Comment by timholy** [comment]
Do you agree this seems like the best "home" for this functionality? To me it seems best on balance, but this is a case where it's not quite "math with RGBs" anymore.

**Comment by AndrewGibb** [comment]
My first thought would be it belonged in ColorTypes; reasoning that if one creates a new numeric-ish type, any of the numeric-ish operations ought to be created alongside. Although with the three color modules, you've made the clear distinction between Color types, which are measurements of color values, and the operations on them which approximate them as a vector space. 

Another reason to include them in ColorTypes is that if a ColorType is a type to represent a measurement, then `rand()` is a way to create dummy data.

To close my 2 cents, almost every use case for the Color group of modules will begin by including all three modules anyway, so agonising over edge cases of where things live isn't that important!

**Comment by timholy** [comment]
> Another reason to include them in ColorTypes is that if a ColorType is a type to represent a measurement, then rand() is a way to create dummy data.

To me this is the most compelling argument---the main concern being, what if someone wants to use `rand` to generate dummy data but would explicitly **not** want to treat them as a vector space.

I think I'll move it to ColorTypes.

**Pull request closed without merging**
