### PR TITLE
Bump requirements to julia-0.7

### PR DESCRIPTION
**Pull request by timholy**
To trigger femtocleaner

### CODE REVIEW

**Comment by cormullion** [comment]
the removal of Compat seems to cause errors

**Comment by SimonDanisch** [comment]
Took the freedom to fix the functionality relying on Compat. Luckily it was just vectorize_arg. Pretty sure that the `vectorize(1/2)_arg` isn't needed anymore with broadcast! Tests pass locally when removing them, so if it was needed, it wasn't even receiving any test coverage.

**Comment by SimonDanisch** [comment]
any veto on a quick merge + tag?! @timholy

**Comment by timholy** [comment]
It still has a heck of a lot of depwarns, and I was thinking we'd want to get rid of those first? I got rid of some in [ColorTypes](https://github.com/JuliaGraphics/ColorTypes.jl/pull/107) and more in my latest commit. But the new stdlib Statistics is going to wreak temporary havoc. We may need to wait for StatsBase to release a new version to really know if they are gone :frowning:.

But I suppose we could tag now if this passes.

**Pull request merged**
