### PR TITLE
Remove Base.ShortCircuiting since it was removed from Base

### LINKED ISSUE #63: Load failing in latest 0.6.0 - "UndefVarError: ShortCircuiting not defined"
Version 0.6.0-dev.1606 (2016-12-18 02:36 UTC)
Commit 08fcc0f (0 days old master)
x86_64-apple-darwin13.4.0

```
ERROR: LoadError: UndefVarError: ShortCircuiting not defined
 in include_from_node1(::String) at ./loading.jl:532
 in include_from_node1(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include(::String) at ./sysimg.jl:14
 in include(::String) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in anonymous at ./<missing>:2
 in eval(::Module, ::Any) at ./boot.jl:236
 in eval(::Module, ::Any) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:269
 in _start() at ./client.jl:356
 in _start() at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/IanB/.julia/v0.6/ColorVectorSpace/src/ColorVectorSpace.jl, in expression starting on line 59
ERROR: Failed to precompile ColorVectorSpace to /Users/IanB/.julia/lib/v0.6/ColorVectorSpace.ji.
 in compilecache(::String) at ./loading.jl:672
 in require(::Symbol) at ./loading.jl:453
 in require(::Symbol) at /Applications/Julia-0.6.app/Contents/Resources/julia/lib/julia/sys.dylib:?
```

### PR DESCRIPTION
**Pull request by ararslan**
Fixes #63

### CODE REVIEW

**Comment by ararslan** [comment]
cc @tkelman

**Comment by tkelman** [comment]
this probably shouldn't be merged without dropping support for julia 0.4

**Comment by ararslan** [comment]
Why's that? The tests all pass on 0.4.

**Comment by tkelman** [comment]
Then the tests aren't specific enough. All functions have the same type on 0.4.

**Comment by ararslan** [comment]
I've submitted a Compat PR that adds `ShortCircuiting`, so if that's merged and Compat is subsequently tagged, we can just bump the required Compat version here.

**Comment by tkelman** [comment]
I'm going to guess @timholy wouldn't mind dropping 0.4 support here. If bugfixes are needed they can always be done from a branch.

**Comment by ararslan** [comment]
Just realized that a Compat solution already exists: `@functorize`. I pushed a commit that should eliminate the ambiguities on 0.4.

**Comment by tkelman** [comment]
Ooh nice. LGTM, remind me tomorrow if no one beats me to merging this.

**Comment by ararslan** [comment]
Don't know how far into today you wanted me to remind you, @tkelman, but it appears no one has beaten you to the merge.

**Comment by timholy** [comment]
For the record, I don't mind dropping 0.4 support.

**Pull request merged**
