### PR TITLE
rename v2

### PR DESCRIPTION
**Pull request by timholy**
CC @SimonDanisch. I just went to the home page, switched the *Branch* from "master" to "rename v2", and clicked the "Pull request" button.

### CODE REVIEW

**Comment by timholy** [comment]
Looks like this still has test errors, see the Travis log.

**Comment by timholy** [comment]
I found this helpful:
```sh
fls=$(find . -name "*.jl")                                                                                                                                                                                                                                                     
sed -i 's/\bColor\b/Colorant/g' $fls                                                                                                                                                                                                                                           
sed -i 's/\bOpaqueColor\b/Color/g' $fls                                                                                                                                                                                                                                        
sed -i 's/\bbasecolortype\b/base_colorant_type/g' $fls
sed -i 's/\bbaseopaquetype\b/base_color_type/g' $fls
sed -i 's/\bopaquetype\b/color_type/g' $fls
sed -i 's/\opaquecolor\b/color/g' $fls
sed -i 's/\bcolor_string\b/colorant_string/g' $fls
sed -i 's/\bColorUfixed\b/ColorantUfixed/g' $fls
```
You shouldn't run the whole thing, just the parts you didn't already do.

**Comment by SimonDanisch** [comment]
Thanks Tim!
Hope this works now.

**Comment by timholy** [comment]
Thanks!

**Pull request merged**
