### PR TITLE
add dot for Gray image (fixes #101)

### LINKED ISSUE #101: dot method not defined
```julia
julia> using ImageCore

julia> using LinearAlgebra

julia> x = rand(Gray, 3, 3)
3×3 Array{Gray{Float64},2} with eltype Gray{Float64}:
 Gray{Float64}(0.54763)   Gray{Float64}(0.684368)  Gray{Float64}(0.213733)
 Gray{Float64}(0.703994)  Gray{Float64}(0.316331)  Gray{Float64}(0.604376)
 Gray{Float64}(0.970118)  Gray{Float64}(0.970798)  Gray{Float64}(0.509367)

julia> dot(channelview(x), channelview(x))
3.9179152985873418

julia> dot(x, x)
ERROR: MethodError: no method matching iterate(::Gray{Float64})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:568
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:568
  iterate(::ExponentialBackOff) at error.jl:199
  ...
Stacktrace:
 [1] dot(::Gray{Float64}, ::Gray{Float64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/generic.jl:673
 [2] dot(::Array{Gray{Float64},2}, ::Array{Gray{Float64},2}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.1/LinearAlgebra/src/generic.jl:728
 [3] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by johnnychen94**
This can be used in 
https://github.com/JuliaImages/Images.jl/blob/1ea7089063593fa81d2b16fd33203001e4c980bd/src/algorithms.jl#L322-L330

### CODE REVIEW

**Comment by johnnychen94** [comment]
Is `dotc` implemented for a similar purpose? If so I think we can deprecate `dotc` in favor of `dot`?

**Comment by timholy** [comment]
Since
```julia
c = RGB(1, 0, 0)
c*c
```
doesn't make sense, I am not sure we can just call this `dot`. Indeed, currently
```julia
julia> g = Gray(0.2f0)
Gray{Float32}(0.2f0)

julia> g*g
Gray{Float32}(0.040000003f0)
```
If we keep this, perhaps I'd change my comment in https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/101#issuecomment-490808702 and say `dot` should error for Gray? But with an informative error message?

**Comment by johnnychen94** [comment]
I thought whatever number operations `op(a::Number, b::Number)` can be expanded to gray operations seamlessly:

```julia
op(a::Number, b::Gray)
op(a::Gray, b::Number)
op(a::Gray, b::Gray)
```

and for Color3 operations, we can expand `op(a::RGB, b::RGB)` if it intuitively makes sense.

**Comment by timholy** [comment]
Without trying to defend the current system too much, note one might quibble about the definition of "intuitive" in [the implementation of `dotc`](https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/371872584639ad9e3415a3826ae655e8bbc5a499/src/ColorVectorSpace.jl#L186). `dotc` was intended to approximately satisfy "psychophysical luminance invariance", e.g.,

```julia
julia> c = RGB(0.2, 0.1, 0.8)
RGB{Float64}(0.2,0.1,0.8)

julia> dotc(c, c)
0.034269999861717235

julia> g = Gray(c)
Gray{Float64}(0.2097000002861023)

julia> dotc(g, g)
0.04397409011999131
```
(not identical, but at least ballpark the same) whereas thinking of an RGB as a 3-vector
```julia
julia> v = [0.2, 0.1, 0.8]
3-element Array{Float64,1}:
 0.2
 0.1
 0.8

julia> dot(v, v)
0.6900000000000002
```
differs by 20x.

The lack of documentation is a major oversight. In defense, I think this package was created before Julia had any internal documentation system whatsoever.

**Comment by johnnychen94** [comment]
I need to carefully rethink about it before I can make more comments.

In the meantime, can you merge this PR so that I can continue my dev in ImageDistances?

**Comment by timholy** [comment]
I'm no longer certain we should, unless we intend to support `dot` for RGB (which I am a bit skeptical about). An alternative would be to modify `ncc` to use, e.g., `mapreduce(xy->dotc(xy...), +, zip(A, B))`?

**Comment by timholy** [comment]
I think the other fix is better, closing.

**Pull request closed without merging**
