### PR TITLE
Fix on 0.7

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like there's some `reinterpret` stuff that's failing on 0.7.

**Comment by timholy** [comment]
I restarted one of the jobs; it might be simply because other PRs hadn't been tagged yet (we'll see).

We might want to add a "deprecation" for `reinterpret(T, ::ReinterpretedArray, sz)`. Yes, that seems silly because we didn't have it before, so why do we need a deprecation? The reason is that this comes up in the context of reinterpreting an array that has already been reinterpreted once. Formerly that would have been `reinterpret(T, ::Array, sz)`. CC @Keno.

**Comment by ararslan** [comment]
Makes sense. We did that recently with `indmin` or something as well IIRC.

**Comment by Keno** [comment]
Makes sense to me to add that deprecation.

**Pull request merged**
